### PR TITLE
Testing: Add a fake implementation of TraceService.

### PR DESCRIPTION
**Pull request by songy23**
This fake server will be used to test against the clients in https://github.com/census-instrumentation/opencensus-java/pull/1476.

Equivalent to https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/blob/master/mock_agent_test.go.

### CODE REVIEW

**Comment by songy23** [comment]
@bogdandrutu I considered putting this fake server under io.opencensus.testing initially. A few concerns about doing so:
1. This will add `io.grpc` and `io.opencensus.proto` dependencies to `io.opencensus.testing`.
2. We have to make the fake server implementation public, while I don't think it will be useful outside the ocagent exporter package.

That being said, I agree that there's no need to include the fake server in the ocagent-exporter artifact. I've moved it to `io.opencensus.testing`.

**Comment by bogdandrutu** [comment]
@songy23 my suggestion was to have it in the src/test/java instead of src/main/java. What do you think?

**Comment by songy23** [comment]
> my suggestion was to have it in the src/test/java instead of src/main/java. What do you think?

SGTM, updated. (though it's a bit strange to have tests for a class under test directory.)

**Comment by songy23** [comment]
> we can move it to the main later but I don't think this should be present in the artifact that gets exported to maven central for example even if this is package protected.

Make sense to me.

**Pull request merged**
