### PR TITLE
Silently skip tags with unknown type during deserialization (issue #655).

### PR DESCRIPTION
**Pull request by sebright**
Now TagContextBinarySerializerImpl.fromByteArray skips unknown tag types instead
of throwing a TagContextParseException.  When the tag has type long or boolean,
it only skips the individual tag.  When the tag has an unknown type, it skips
the rest of the input, since it doesn't know the tag's length.

EDIT:
This change will increase compatibility between the first version of the tagging
implementation and later versions, because the first version will be able to
accept tags that it supports, even if they are mixed with tags that it doesn't
support.

/cc @adriancole

### CODE REVIEW

**Comment by songy23** [comment]
I would prefer throwing exception for unsupported tags instead. I think it might be better to hard crash users' code when there's an incompatibility between tagging versions, so that they know it's time to update their serialization code.

**Comment by sebright** [comment]
@songy23 This PR is based on the Serialization Rules and Deserialization Rules sections of [BinaryEncoding.md](https://github.com/census-instrumentation/opencensus-specs/blob/master/encodings/BinaryEncoding.md) in opencensus-specs.  I think that if we throw exceptions for unrecognized fields, we should also update opencensus-specs.  I opened an issue for adding more details on how to handle invalid input, which relates to this issue: https://github.com/census-instrumentation/opencensus-specs/issues/12

**Comment by bogdandrutu** [comment]
I think we are a stats/trace/debugging library and we should not crash user's binary for these kind of reasons.

**Comment by songy23** [comment]
I think we're going to remove long and boolean typed tags, may be better to hold off this change after discussion on that.

**Comment by sebright** [comment]
Yes, I'll also need to rebase this onto #710.

**Comment by sebright** [comment]
I opened a new PR (#715) instead of rebasing this onto #710, since I needed to make significant changes.

**Pull request closed without merging**
