### PR TITLE
Rename StatsRunner to TagContextExample because it's more about TagContext.

### PR DESCRIPTION
**Pull request by songy23**
Closes https://github.com/census-instrumentation/opencensus-java/issues/1154.

### CODE REVIEW

**Comment by sebright** [comment]
"Runner" also seems a little unclear to me.  What about something like "Tagging API Example" or "TagContext Example"?

**Comment by songy23** [comment]
`TagContextExample` sounds better - updated.

**Comment by songy23** [comment]
Thanks!

**Comment by songy23** [comment]
Thanks!

**Pull request merged**
