### PR TITLE
Use AppEngine compatible way to create threads. (fixes #707 and #777)

### LINKED ISSUE #707: Not AppEngine/Java7-compatible when creating new threads
I found two places where Census creates its own thread, not sure if there is more:
 1. [io.opencensus.impl.internal.DisruptorEventQueue.java](https://github.com/census-instrumentation/opencensus-java/blob/v0.7.0/impl/src/main/java/io/opencensus/impl/internal/DisruptorEventQueue.java#L144)
 2. [io.opencensus.implcore.trace.export.SpanExporterImpl](https://github.com/census-instrumentation/opencensus-java/blob/v0.7.0/impl_core/src/main/java/io/opencensus/implcore/trace/export/SpanExporterImpl.java#L94)

When running in restricted AppEngine (Java 7), gRPC creates the thread through [MoreExecutors.platformThreadFactory()](https://github.com/grpc/grpc-java/blob/v1.7.0/core/src/main/java/io/grpc/internal/GrpcUtil.java#L517). As Census is used in gRPC and expected to be used in AppEngine, it should probably do the same.

/cc @ejona86, @carl-mastrangelo

### PR DESCRIPTION
**Pull request by HailongWen**
This fixes the compatibility issue in GAE Java 7.
Please refer to [comment](https://github.com/census-instrumentation/opencensus-java/pull/868#issuecomment-348715397) for test result details.

- Summary
GAE Java 7 forbids spawning new threads manually (see [link](https://cloud.google.com/appengine/docs/standard/java/javadoc/com/google/appengine/api/ThreadManager) for detail). Besides, modifying thread name and setting as daemon are also prohibited. 

- Solution
As recommended [here](https://github.com/grpc/grpc-java/blob/v1.7.0/core/src/main/java/io/grpc/internal/GrpcUtil.java#L517).
  - Refactor `DaemonThreadFactory` to utilize `MoreExecutors`
  - Change `SpanExporterImpl#WorkerThread` to `Runnable` and use `DaemonThreadFactory` to perform creation.

### CODE REVIEW

**Comment by HailongWen** [comment]
Here are the test results with java7/8, opencensus-impl/lite and before/after patch.

To conclude:
- With GAE Java 8, we have no compatibility issues and both impl and impl-lite can be used.
- With GAE Java 7
  - impl will always fail (with or without patch) due to lack of unsafe support
  - impl-lite will fail if we spawn threads or modify them (`setName` or `setDaemon`). This patch uses compatible `ThreadFactory` to create thread and skips modifying thread if in GAE Java 7. By doing so, tests of impl-lite can pass.

package/test result/environment  | GAE Java 7 | GAE Java 8
------------ | ------------ | -------------
opencensus-impl-0.10.0 | [Failure](https://gist.github.com/HailongWen/55205709f8f70d6e7e120143f05bbc91) | [Success](https://gist.github.com/HailongWen/fef7f50b3ed8669fb10156745bdb3d62)
opencensus-impl-lite-0.10.0 | [Failure](https://gist.github.com/HailongWen/441ae39dc6a4bdf7cdcd08d607e4ae9a) | [Success](https://gist.github.com/HailongWen/a3bb9885b687c63bb88a0c3701b554d7)
opencensus-impl-0.10.0 (patched) | [Failure](https://gist.github.com/HailongWen/6677c489c3992676e34fbbca34e5e41b) | [Success](https://gist.github.com/HailongWen/001fb36bdf53109e50f4d18fed99f885)
opencensus-impl-lite-0.10.0 (patched)| [Success](https://gist.github.com/HailongWen/2e2c977fe1c54c863018c17703289817) | [Success](https://gist.github.com/HailongWen/9879ebd8863cfb8d33f9aed30992fd87)

**Comment by HailongWen** [comment]
@bogdandrutu I followed the steps in https://github.com/grpc/grpc-java/tree/master/gae-interop-testing to run the gRPC interop test, and manually changed the deps to point to my local built libraries. 

The tests are deployed to GAE with opencensus enabled. With this patch we can successfully run census-impl-lite in GAE Java 7.

**Comment by HailongWen** [comment]
@bogdandrutu do you mean we should also add GAE integration test?

**Comment by bogdandrutu** [comment]
SG. maybe create an issue for us to have an integration test to make sure we don't break the compatibility in the future.

**Comment by HailongWen** [comment]
Added #871 to follow up with the inter-op tesing.

**Pull request merged**
