### PR TITLE
Fixed bug that made it impossible to use short span id's (#950)

### PR DESCRIPTION
**Pull request by songy23**
(cherry picked from commit 765318b5ec65fa840961ecc12d8e3683a861ccec)

### CODE REVIEW

**Comment by bogdandrutu** [comment]
@rlindooren can you create a cherry-pick to our release branch (v0.11.x), use this command:
git cherry-pick 765318b5ec65fa840961ecc12d8e3683a861ccec -x

**Comment by rlindooren** [comment]
@bogdandrutu I'm not allowed to push to v0.11.x. Therefore I created a PR: https://github.com/census-instrumentation/opencensus-java/pull/954 is this what you need for consent?

**Comment by songy23** [comment]
@rlindooren That's right, we have branch protection for v0.11.x as well so a PR is fine.

**Comment by rlindooren** [comment]
@songy23 Ok

**Pull request closed without merging**
