### PR TITLE
Update google-auth-library-credentials.

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Looks like truth 0.36 is not java6 compatible, should we postpone the update? grpc already switched to this version.

**Comment by sebright** [comment]
It might be easier to postpone the upgrade.  Are there any other reasons that we should upgrade soon, such as deprecation of APIs?

**Comment by songy23** [comment]
Postpone sounds good to me, if this update is not in urgent need.

**Comment by bogdandrutu** [comment]
Reverted the truth update for the moment.

**Pull request merged**
