### PR TITLE
Cherrypick #2043 into V0.27.x

### PR DESCRIPTION
**Pull request by zoercai**
I'm making a patch 0.27.1 with #2043 cherrypicked into V0.27.x. I couldn't push directly to v0.27.x because of protected branch rules.

### CODE REVIEW

**Review by nilebox — APPROVED** [review]

**Comment by zoercai** [comment]
@spkrka could you please sign the CLA (https://github.com/census-instrumentation/opencensus-java/pull/2055#issuecomment-698246548) so I can merge this?
Thanks!

**Comment by spkrka** [comment]
I don't understand what's wrong with the CLA.
Looking at https://github.com/census-instrumentation/opencensus-java/pull/2043 it says `cla: yes` - otherwise that PR should not have been possible to merge I think.

When I visit https://cla.developers.google.com/clas it says:

Agreement | Name | Date Signed
-- | -- | --
Google Corporate CLA | Spotify AB | Jun 18, 2014 17:00 PDT

**Comment by spkrka** [comment]
This is the commit from the original PR: https://github.com/census-instrumentation/opencensus-java/pull/2043/commits/8da54660af7daa2b8c5f81764f967af5d3e3f239
It has my email set to `krka@spotify.com` and it passes the CLA.

Then it was merged into master by @nilebox as this commit: https://github.com/census-instrumentation/opencensus-java/commit/eab6382e06f16e7efeb1f9b6cb3eb0c79ee62bbc
That one has the email set to `spkrka@users.noreply.github.com`

I don't know why the github merge operation caused that kind of re-write to the commit, and I don't know how to resolve it.

**Comment by spkrka** [comment]
PR commit:
```
commit 8da54660af7daa2b8c5f81764f967af5d3e3f239 (HEAD -> krka/no_finalize, krka/krka/no_finalize)
Author: Kristofer Karlsson <krka@spotify.com>
Date:   Thu Jul 16 13:13:10 2020 +0200
```
Master commit:
```
commit eab6382e06f16e7efeb1f9b6cb3eb0c79ee62bbc (origin/master, origin/HEAD)
Author: Kristofer Karlsson <spkrka@users.noreply.github.com>
Date:   Tue Sep 22 07:33:18 2020 +0200
```

**Comment by nilebox** [comment]
> That one has the email set to spkrka@users.noreply.github.com
> I don't know why the github merge operation caused that kind of re-write to the commit, and I don't know how to resolve it.

I can confirm that that's the issue with CLA.
@spkrka would you be okay with us rewriting git history with me or @zoercai "taking over" the ownership of the commit from your PR which blocks this change?

**Comment by nilebox** [comment]
@spkrka also please be aware that this PR just cherry-picks a commit from `master` to `v0.27.x` branch.
We have already published the `0.27.1` release which includes the bug fix you're interested.
It's already available in Maven Central: https://repo1.maven.org/maven2/io/opencensus/opencensus-impl/0.27.1/
So you can update your dependencies to using it already.

**Comment by spkrka** [comment]
Yes, I am ok with you rewriting the git history (This was only removing code anyway, so it's not like my change is particularly noteworthy)

**Pull request merged**
