### PR TITLE
Refactor MeasureMap.Builder

### PR DESCRIPTION
**Pull request by songy23**
1. Rename MeasureMap.Builder.set() to put(). Consistent with TagContextBuilder #627 
2. Overwrite existing Measure values, if there are subsequent updates to a Measure that is already put.

### CODE REVIEW

**Comment by sebright** [comment]
I agree with this change, though I think we should also make the builder keep the last value for a Measure so that the behavior is consistent with `Map.put`.

**Comment by dinooliva** [comment]
It may make more sense to stay consistent with the behavior of: https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/ImmutableMap.Builder.html#put(K, V)

**Comment by sebright** [comment]
> It may make more sense to stay consistent with the behavior of: https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/ImmutableMap.Builder.html#put(K, V)

I think we should avoid throwing exceptions during stats recording, if there is another option.  It might be hard for users to ensure that they aren't recording duplicate measures at compile time, or test all instrumented code.

**Comment by songy23** [comment]
I updated MeasureMap.Builder.build() so that only the latest value for a Measure will be picked. This is equivalent to overwriting existing Measure values in put().

**Comment by dinooliva** [comment]
Agree - using the last value is better than throwing an exception.

**Pull request merged**
