### PR TITLE
Fixes copy/paste errors

### PR DESCRIPTION
**Pull request by adriancole**
@jorgheymans and I noticed when plotting brave+census integration

### CODE REVIEW

**Comment by bogdandrutu** [comment]
@songy23 please update the CONTRIBUTION.md with this requirement before sending a PR.

**Comment by songy23** [comment]
Posted https://github.com/census-instrumentation/opencensus-java/pull/1035 to update CONTRIBUTING.

**Comment by adriancole** [comment]
reformat complete!

**Comment by songy23** [comment]
Thanks!

**Pull request merged**
