### PR TITLE
Provide creating scope for async request http-servlet.

### PR DESCRIPTION
**Pull request by rghetia**

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Consider to add a comment in the readme.

**Comment by rghetia** [comment]
@bogdandrutu PTAL again.
Appveyor build failure is not related to the change.

**Comment by bogdandrutu** [comment]
Unfortunately this cannot be in 0.19.1 because it adds a new API, I think we should make 0.19.1 now with the rollback PR and this will get to 0.20.0

**Comment by rghetia** [comment]
> Unfortunately this cannot be in 0.19.1 because it adds a new API, I think we should make 0.19.1 now with the rollback PR and this will get to 0.20.0

SG.

**Pull request merged**
