### PR TITLE
Metrics: Move metrics to opencensus-api.

### PR DESCRIPTION
**Pull request by songy23**
Move `metrics` to `opencensus-api`, for two reasons:

- `metrics` depends on `opencensus-api` (`api-common`), and later `opencensus-api` (`api-stats`) needs to depend on `metrics`. If `metrics` continue to be an independent artifact, this will introduce circular dependency.
- Now that we have `MetricsComponent` and need to reflectively load the implementation, it's reasonable to separate the API and implementation of `metrics`.

### CODE REVIEW

**Comment by songy23** [comment]
Holding off this PR for the moment, since we want to finish the data models first.

**Comment by bogdandrutu** [comment]
Please write a big warning in the package-info that this package (classes from io.opencensus.metrics* are very experimental and users should be aware that we may change them in the future).

**Comment by songy23** [comment]
> Please write a big warning in the package-info that this package (classes from io.opencensus.metrics* are very experimental and users should be aware that we may change them in the future).

SG, I updated `package-info.java` about the potential backwards-incompatible changes in `metrics`.

**Comment by songy23** [comment]
Rebased, going to merge this PR once CI is green.

**Pull request merged**
