### PR TITLE
Remove stackdriver dependencyConvergence failure list because they are not clean.

### PR DESCRIPTION
**Pull request by bogdandrutu**
They bring multiple dependencies for protobuf.

### CODE REVIEW

**Comment by sebright** [comment]
Did the dependency convergence test start failing recently?

**Comment by bogdandrutu** [comment]
Currently I see only warnings in Idea:
Warning:<i><b>root project 'opencensus-java': Unable to resolve additional project configuration.</b>
Details: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':opencensus-exporter-stats-stackdriver:compile'.
Caused by: java.lang.RuntimeException: A conflict was found between the following modules:
 - com.google.protobuf:protobuf-java:3.5.1
 - com.google.protobuf:protobuf-java:3.4.0</i>

I am trying to understand how to make it really fail in the build.

**Comment by bogdandrutu** [comment]
Managed to reproduce the failure with a gradle command:
`./gradlew opencensus-exporter-stats-stackdriver:dependencies`

**Comment by sebright** [comment]
Does that mean that we aren't currently running the check in CI?  Do you want to also add that command to the script?

**Comment by bogdandrutu** [comment]
Correct we do not check this in CI. Trying to see what is the best command to do that. I created an issue https://github.com/census-instrumentation/opencensus-java/issues/1030

**Pull request merged**
