### PR TITLE
WIP - create a span from explicit span context

### PR DESCRIPTION
**Pull request by dmichel1**
Took a shot at implementing https://github.com/census-instrumentation/opencensus-java/issues/1684 - before I refactor `SpanBuilderImpl` too much what do you think of the general idea?

Thanks

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Hi @dmichel1,

I have a different opinion on this, what about we change the spanBuilderWithRemoteParent and if the SpanContext contains a valid TraceId we preserve that?

**Comment by dmichel1** [comment]
hi @bogdandrutu -

That would work but currently the 2nd argument for spanBuilderWithRemoteParent is a Span. I havn't been able to find a way with the current API to build a span with an explicit context. Or where you thinking of changing the method signature of spanBuilderWithRemoteParent to something else?

**Comment by bogdandrutu** [comment]
public abstract SpanBuilder spanBuilderWithRemoteParent(
      String spanName, @Nullable SpanContext remoteParentSpanContext);

It is a SpanContext

**Comment by dmichel1** [comment]
I was getting mixed up with `spanBuilderWithExplicitParent` my mistake. I just got something working locally. This is a better approach than this PR. Closing and will open a different one.

**Pull request closed without merging**
