### PR TITLE
Rename RpcMeasureConstants, declare constants as MeasureDouble.

### PR DESCRIPTION
**Pull request by songy23**
This PR is built on top of #414, I'll rebase this PR once I've merged PR #414.

### CODE REVIEW

**Comment by adriancole** [comment]
Rationale for all measure constants being double? Perhaps this is because
measure type are required to hold any summarized or aggregated value? I ask
because i dont expect to "measure" a fraction of an error.. maybe add some
type or otherwise javadoc of when long would ever be used if not for
counts..

On 6 Jul 2017 05:31, "Yang Song" <notifications@github.com> wrote:

This PR is built on top of #414
<https://github.com/census-instrumentation/opencensus-java/pull/414>, I'll
rebase this PR once I've merged PR #414
<https://github.com/census-instrumentation/opencensus-java/pull/414>.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/census-instrumentation/opencensus-java/pull/415
Commit Summary

   - Refactor MeasureValue.
   - Rename MeasurementMap to MeasureMap.
   - Make Measurement constructor private.
   - Remove a few redundant methods, add tests.
   - Remove unnessary testOrder() for MeasureMap.
   - Rename Measure and Measurement subclasses.
   - Rename RpcMeasureConstants, declare constants as MeasureDouble.

File Changes

   - *M* core/src/main/java/io/opencensus/stats/Measure.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-0>
   (30)
   - *A* core/src/main/java/io/opencensus/stats/MeasureMap.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-1>
   (127)
   - *A* core/src/main/java/io/opencensus/stats/Measurement.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-2>
   (86)
   - *D* core/src/main/java/io/opencensus/stats/MeasurementMap.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-3>
   (147)
   - *D* core/src/main/java/io/opencensus/stats/MeasurementValue.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-4>
   (49)
   - *R* core/src/main/java/io/opencensus/stats/RpcMeasureConstants.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-5>
   (94)
   - *M* core/src/main/java/io/opencensus/stats/RpcViewConstants.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-6>
   (50)
   - *M* core/src/main/java/io/opencensus/stats/StatsContext.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-7>
   (2)
   - *M* core/src/main/java/io/opencensus/stats/StatsRecorder.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-8>
   (2)
   - *A* core/src/test/java/io/opencensus/stats/MeasureMapTest.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-9>
   (163)
   - *M* core/src/test/java/io/opencensus/stats/MeasureTest.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-10>
   (32)
   - *D* core/src/test/java/io/opencensus/stats/MeasurementMapTest.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-11>
   (116)
   - *A* core/src/test/java/io/opencensus/stats/RpcMeasureConstantsTest.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-12>
   (64)
   - *D* core/src/test/java/io/opencensus/stats/RpcMeasurementConstantsTest.
   java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-13>
   (64)
   - *M* core/src/test/java/io/opencensus/stats/ViewDescriptorTest.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-14>
   (2)
   - *M* core/src/test/java/io/opencensus/stats/ViewTest.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-15>
   (2)
   - *M* core_impl/src/main/java/io/opencensus/stats/MeasureToViewMap.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-16>
   (38)
   - *M* core_impl/src/main/java/io/opencensus/stats/StatsContextImpl.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-17>
   (2)
   - *M* core_impl/src/main/java/io/opencensus/stats/StatsManager.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-18>
   (6)
   - *M* core_impl/src/main/java/io/opencensus/stats/StatsRecorderImpl.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-19>
   (2)
   - *M* core_impl/src/test/java/io/opencensus/stats/
   MeasureToViewMapTest.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-20>
   (5)
   - *M* core_impl/src/test/java/io/opencensus/stats/StatsContextTest.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-21>
   (48)
   - *M* core_impl/src/test/java/io/opencensus/stats/
   ViewManagerImplTest.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-22>
   (66)
   - *M* examples/src/main/java/io/opencensus/examples/stats/
   StatsRunner.java
   <https://github.com/census-instrumentation/opencensus-java/pull/415/files#diff-23>
   (20)

Patch Links:

   - https://github.com/census-instrumentation/opencensus-
   java/pull/415.patch
   - https://github.com/census-instrumentation/opencensus-java/pull/415.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/census-instrumentation/opencensus-java/pull/415>, or mute
the thread

**Comment by songy23** [comment]
@adriancole It's totally correct that *_COUNT constants should use MeasureLong instead of Double, but we haven't decided yet whether we would support MeasureLong in v0.1. I've put a TODO on top of RpcMeasureConstants: https://github.com/census-instrumentation/opencensus-java/blob/master/core/src/main/java/io/opencensus/stats/RpcMeasurementConstants.java#L19.

**Comment by adriancole** [comment]
thx!

**Comment by songy23** [comment]
Rebased, going to merge...

**Pull request merged**
