### PR TITLE
Disallow empty tag keys.

### PR DESCRIPTION
**Pull request by sebright**
Do you think we should add this restriction to tag keys?

### CODE REVIEW

**Comment by dinooliva** [comment]
I don't see any particular reason to disallow empty tag keys. Eventually we'll likely have a specified format that tag keys will need to follow but I don't see an advantage to adding this as a special case now.

**Comment by sebright** [comment]
@dinooliva I thought that it would be better to try to enforce all restrictions in the first release, for backwards compatibility.  What format do you think we'll need to enforce later?

**Comment by dinooliva** [comment]
There is no agreed upon format so far, unfortunately - I'll look into it and see if we can resolve this soon.

**Comment by sebright** [comment]
I created an issue: #525

**Comment by songy23** [comment]
Please rebase.

**Comment by sebright** [comment]
I rebased

**Comment by sebright** [comment]
I discussed this with @dinooliva and others, and we are going to disallow empty tag keys in the first release.

**Pull request merged**
