### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by songy23**
Fixes https://github.com/census-instrumentation/opencensus-java/issues/1327.

### CODE REVIEW

**Comment by bogdandrutu** [comment]
com.google.code.findbugs:annotations:3.0.2 does not exist. Maybe stick with 3.0.1 for this.

**Comment by songy23** [comment]
> com.google.code.findbugs:annotations:3.0.2 does not exist. Maybe stick with 3.0.1 for this.

Yes 3.0.1 is more stable. Updated to that version.

**Comment by bogdandrutu** [comment]
For truth the latest version in maven seems to be 0.42

**Comment by songy23** [comment]
> For truth the latest version in maven seems to be 0.42

Exactly - thanks!

**Comment by bogdandrutu** [comment]
Just go with an earlier truth version for the moment. grpc uses 0.36 for example.

**Comment by songy23** [comment]
Still no luck - I reverted the version of `truth` for now.

**Comment by bogdandrutu** [comment]
@songy23 the initial version was 0.30

**Comment by songy23** [comment]
> the initial version was 0.30

Yes, corrected. Filed https://github.com/census-instrumentation/opencensus-java/issues/1333 for further investigation of the build issues for contrib/agent.

**Comment by elharo** [comment]
Not sure about the annotations library. The findbugs issue I was referencing was for jsr 3.0.5. That is,

compile 'com.google.code.findbugs:jsr305:3.0.2'

It may be necessary to split the version of the annotations and the jsr305 packages.

**Comment by songy23** [comment]
@elharo I see, sent https://github.com/census-instrumentation/opencensus-java/pull/1335 to update.

**Pull request merged**
