### PR TITLE
Map http attributes to the stackdriver format, resolves #1153

### LINKED ISSUE #1153: HTTP Attributes are not mapped in Stackdriver exporter
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
0.12.3

### What JVM are you using (`java -version`)?
8

### What did you do?
Adding http attributes according to the [spec](https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/HTTP.md) to a span (http.host, http.method, ...), see here: https://github.com/Sebruck/opencensus-scala/blob/master/akka-http/src/main/scala/com/github/sebruck/opencensus/akka/http/trace/HttpAttributes.scala#L16

### What did you expect to see?
The spec defines that those attributes should be mapped when exporting to stackdriver, e.g.:
`http.host` -> `/http/host`

But this seems not to happen, in Stackdriver I still see the initial value.

I also can't find any code doing this in the `opencensus-exporter-trace-stackdriver` module.

### What did you see instead?
The attributes should be mapped as defined in the specs.

Is this a missing feature or a bug?

### PR DESCRIPTION
**Pull request by Sebruck**
@sebright  WDYT?

### CODE REVIEW

**Comment by Sebruck** [comment]
I signed it!

**Comment by Sebruck** [comment]
@sebright build is now green

**Comment by sebright** [comment]
Thanks!

**Comment by Sebruck** [comment]
@sebright thanks for merging! Would it be possible to do a patch release please?

**Comment by songy23** [comment]
@Sebruck sure, I can do a patch release for this change today.

**Comment by songy23** [comment]
Sorry I just realized that CLA doesn't allow cherry-pick commits from other contributors, only owner of that commit can do so. @Sebruck can you cherry-pick your commit to branch `v0.13.x` and make a PR? 

`$ git checkout -b v0.13.x upstream/v0.13.x`
`$ git cherry-pick -x a1a6cf16ec5e6ec3c1e08e96b1e8dd9a45dce13e`

**Comment by songy23** [comment]
OK, I got CLA work by manually adding a cla:yes label.

Please ignore my last comment, https://github.com/census-instrumentation/opencensus-java/pull/1185 should be good now.

**Comment by Sebruck** [comment]
screen shot 2018-05-09 at 08 46 35

Just wanted to let you know that it works now, however stackdriver trace seems to be not handle host and user_agent in the same way as the other http attributes.

**Pull request merged**
