### PR TITLE
enable javadoc for jetty client. (#1734)

### PR DESCRIPTION
**Pull request by rghetia**
(cherry picked from commit 1224f0ab8dc2e064d10cefb4e1ec0726d92089b9)

### CODE REVIEW

**Comment by songy23** [comment]
Not sure if this should go into a patch release or a minor release?

**Comment by bogdandrutu** [comment]
Please use the cherry pick command, it will fill the description nicely.

**Comment by songy23** [comment]
`'git cherry-pick -x 1224f0a`

**Comment by rghetia** [comment]
> `'git cherry-pick -x 1224f0a`

thanks @songy23 . I'll use it next time. for now I updated the description as it would be done by -x option.

**Comment by rghetia** [comment]
> Not sure if this should go into a patch release or a minor release?

I think it should go in patch release.

@bogdandrutu what are your thoughts?

**Comment by bogdandrutu** [comment]
I am fine with the cherry-pick and if we will have to do a new patch release it will get deployed. I am not 100% convinced that we should do it right now the patch release.

**Comment by rghetia** [comment]
> I think we should include the proper fix for #1709 in the next patch release.

fix for #1709 requires new api. So it cannot be in patch release.

**Comment by odeke-em** [comment]
Hey folks, after this PR closed that issue, perhaps something got deployed but the JavaDoc for http-jetty-client still doesn't appear at https://www.javadoc.io/doc/io.opencensus/opencensus-contrib-http-jetty-client/0.19.1

screen shot 2019-02-05 at 4 32 52 pm

**Comment by bogdandrutu** [comment]
We cannot deploy anything without a patch or a minor release.

**Comment by bogdandrutu** [comment]
@odeke-em we will do a patch release today for a different bug so the javadoc will be available for 0.19.2

**Comment by songy23** [comment]
FYI Javadoc is available on https://www.javadoc.io/doc/io.opencensus/opencensus-contrib-http-jetty-client/0.19.2.

**Pull request merged**
